In [2]:
import torch.nn as nn
import numpy as np
import pandas as pd
import torch

# TLDR CrossEntropyLoss works with both class indices and class probabilities as inputs for the target. For the predictions, they do not have to be between 0 and 1. There is an inbuilt softmax function

In [7]:
# Example of target with class indices
loss = nn.CrossEntropyLoss()
input = torch.randn(3, 5, requires_grad=True)
target = torch.empty(3, dtype=torch.long).random_(5)
output = loss(input, target)
output.backward()
output, input, target # I see. Just the raw logits from the model would do.

(tensor(1.8856, grad_fn=<NllLossBackward0>),
 tensor([[ 1.5344,  0.5114, -1.7069,  0.1978,  1.2031],
         [ 1.2939,  0.7978, -0.7781,  0.6881,  1.0498],
         [ 0.8508, -0.4573,  1.5410,  0.3770, -0.4541]], requires_grad=True),
 tensor([4, 3, 1]))

In [9]:
# Example of target with class probabilities
input = torch.randn(3, 5, requires_grad=True) # does not have to be in [0,1]
target = torch.randn(3, 5).softmax(dim=1) 
output = loss(input, target)
output.backward()
output, input, target # Both work, actually

(tensor(2.1223, grad_fn=<DivBackward1>),
 tensor([[-0.9275,  1.6700, -1.4788,  1.2130, -1.0821],
         [-0.4786,  0.2991,  0.4053,  0.7525, -1.3179],
         [ 1.2246, -0.0024,  0.1720,  0.4070,  1.0896]], requires_grad=True),
 tensor([[0.7784, 0.0134, 0.0541, 0.0181, 0.1358],
         [0.0160, 0.0122, 0.2903, 0.4775, 0.2040],
         [0.0338, 0.2566, 0.0769, 0.0985, 0.5342]]))

In [1]:
import re
string = "/pool001/mrx/projects/affinity/ntk_matrix_completion/output/2023_multitask/multitask_2023218_172227"
pattern = "/pool001/mrx/projects/affinity"
replacement = "/home/mrx/projects/affinity_pool"
re.sub(pattern, replacement, string, count=0, flags=0)

'/home/mrx/projects/affinity_pool/ntk_matrix_completion/output/2023_multitask/multitask_2023218_172227'